version: "3.7"
services:
  order-db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always

#  app:
#    image: app
#    ports:
#      - "8080:8080"
#    build: .
#
#    restart: always
